
package PersonSoapClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersonSoapClientServiceService", targetNamespace = "http://Client.SOAP_WebServices/", wsdlLocation = "http://DESKTOP-VK3DF3H:8080/Sample_Project-1.0-SNAPSHOT/PersonSoapClientServiceService?wsdl")
public class PersonSoapClientServiceService
    extends Service
{

    private final static URL PERSONSOAPCLIENTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PERSONSOAPCLIENTSERVICESERVICE_EXCEPTION;
    private final static QName PERSONSOAPCLIENTSERVICESERVICE_QNAME = new QName("http://Client.SOAP_WebServices/", "PersonSoapClientServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://DESKTOP-VK3DF3H:8080/Sample_Project-1.0-SNAPSHOT/PersonSoapClientServiceService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONSOAPCLIENTSERVICESERVICE_WSDL_LOCATION = url;
        PERSONSOAPCLIENTSERVICESERVICE_EXCEPTION = e;
    }

    public PersonSoapClientServiceService() {
        super(__getWsdlLocation(), PERSONSOAPCLIENTSERVICESERVICE_QNAME);
    }

    public PersonSoapClientServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONSOAPCLIENTSERVICESERVICE_QNAME, features);
    }

    public PersonSoapClientServiceService(URL wsdlLocation) {
        super(wsdlLocation, PERSONSOAPCLIENTSERVICESERVICE_QNAME);
    }

    public PersonSoapClientServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONSOAPCLIENTSERVICESERVICE_QNAME, features);
    }

    public PersonSoapClientServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonSoapClientServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns PersonSoapClientService
     */
    @WebEndpoint(name = "PersonSoapClientServicePort")
    public PersonSoapClient.PersonSoapClientService getPersonSoapClientServicePort() {
        return super.getPort(new QName("http://Client.SOAP_WebServices/", "PersonSoapClientServicePort"), PersonSoapClientService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonSoapClientService
     */
    @WebEndpoint(name = "PersonSoapClientServicePort")
    public PersonSoapClientService getPersonSoapClientServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Client.SOAP_WebServices/", "PersonSoapClientServicePort"), PersonSoapClientService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONSOAPCLIENTSERVICESERVICE_EXCEPTION!= null) {
            throw PERSONSOAPCLIENTSERVICESERVICE_EXCEPTION;
        }
        return PERSONSOAPCLIENTSERVICESERVICE_WSDL_LOCATION;
    }

}
