
package PersonSoapClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonSoapClientService", targetNamespace = "http://Client.SOAP_WebServices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonSoapClientService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteUserById")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "DeleteUserById", targetNamespace = "http://Client.SOAP_WebServices/", className = "PersonSoapClient.DeleteUserById")
    @ResponseWrapper(localName = "DeleteUserByIdResponse", targetNamespace = "http://Client.SOAP_WebServices/", className = "PersonSoapClient.DeleteUserByIdResponse")
    @Action(input = "http://Client.SOAP_WebServices/PersonSoapClientService/DeleteUserByIdRequest", output = "http://Client.SOAP_WebServices/PersonSoapClientService/DeleteUserByIdResponse")
    public String deleteUserById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeletDriverById")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "DeletDriverById", targetNamespace = "http://Client.SOAP_WebServices/", className = "PersonSoapClient.DeletDriverById")
    @ResponseWrapper(localName = "DeletDriverByIdResponse", targetNamespace = "http://Client.SOAP_WebServices/", className = "PersonSoapClient.DeletDriverByIdResponse")
    @Action(input = "http://Client.SOAP_WebServices/PersonSoapClientService/DeletDriverByIdRequest", output = "http://Client.SOAP_WebServices/PersonSoapClientService/DeletDriverByIdResponse")
    public String deletDriverById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
