
package personSoapClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "personSoapClientService", targetNamespace = "http://client.soap.service.transportationbookingsystem.exalt.com/", wsdlLocation = "http://DESKTOP-VK3DF3H:8080/transportation-booking-system-1.0-SNAPSHOT/personSoapClientService?wsdl")
public class PersonSoapClientService
    extends Service
{

    private final static URL PERSONSOAPCLIENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PERSONSOAPCLIENTSERVICE_EXCEPTION;
    private final static QName PERSONSOAPCLIENTSERVICE_QNAME = new QName("http://client.soap.service.transportationbookingsystem.exalt.com/", "personSoapClientService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://DESKTOP-VK3DF3H:8080/transportation-booking-system-1.0-SNAPSHOT/personSoapClientService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONSOAPCLIENTSERVICE_WSDL_LOCATION = url;
        PERSONSOAPCLIENTSERVICE_EXCEPTION = e;
    }

    public PersonSoapClientService() {
        super(__getWsdlLocation(), PERSONSOAPCLIENTSERVICE_QNAME);
    }

    public PersonSoapClientService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONSOAPCLIENTSERVICE_QNAME, features);
    }

    public PersonSoapClientService(URL wsdlLocation) {
        super(wsdlLocation, PERSONSOAPCLIENTSERVICE_QNAME);
    }

    public PersonSoapClientService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONSOAPCLIENTSERVICE_QNAME, features);
    }

    public PersonSoapClientService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonSoapClientService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns PersonSoapClient
     */
    @WebEndpoint(name = "personSoapClientPort")
    public personSoapClient.PersonSoapClient getPersonSoapClientPort() {
        return super.getPort(new QName("http://client.soap.service.transportationbookingsystem.exalt.com/", "personSoapClientPort"), PersonSoapClient.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonSoapClient
     */
    @WebEndpoint(name = "personSoapClientPort")
    public PersonSoapClient getPersonSoapClientPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://client.soap.service.transportationbookingsystem.exalt.com/", "personSoapClientPort"), PersonSoapClient.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONSOAPCLIENTSERVICE_EXCEPTION!= null) {
            throw PERSONSOAPCLIENTSERVICE_EXCEPTION;
        }
        return PERSONSOAPCLIENTSERVICE_WSDL_LOCATION;
    }

}
