
package personSoapClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "personSoapClient", targetNamespace = "http://client.soap.service.transportationbookingsystem.exalt.com/")
@XmlSeeAlso({
    personSoapClient.ObjectFactory.class
})
public interface PersonSoapClient {


    /**
     * 
     * @param arg0
     * @throws tripSoapClient.NotFoundException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteDriverById", targetNamespace = "http://client.soap.service.transportationbookingsystem.exalt.com/", className = "personSoapClient.DeleteDriverById")
    @ResponseWrapper(localName = "deleteDriverByIdResponse", targetNamespace = "http://client.soap.service.transportationbookingsystem.exalt.com/", className = "personSoapClient.DeleteDriverByIdResponse")
    @Action(input = "http://client.soap.service.transportationbookingsystem.exalt.com/personSoapClient/deleteDriverByIdRequest", output = "http://client.soap.service.transportationbookingsystem.exalt.com/personSoapClient/deleteDriverByIdResponse", fault = {
        @FaultAction(className = personSoapClient.NotFoundException_Exception.class, value = "http://client.soap.service.transportationbookingsystem.exalt.com/personSoapClient/deleteDriverById/Fault/NotFoundException")
    })
    public void deleteDriverById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws personSoapClient.NotFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws personSoapClient.NotFoundException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUserById", targetNamespace = "http://client.soap.service.transportationbookingsystem.exalt.com/", className = "personSoapClient.DeleteUserById")
    @ResponseWrapper(localName = "deleteUserByIdResponse", targetNamespace = "http://client.soap.service.transportationbookingsystem.exalt.com/", className = "personSoapClient.DeleteUserByIdResponse")
    @Action(input = "http://client.soap.service.transportationbookingsystem.exalt.com/personSoapClient/deleteUserByIdRequest", output = "http://client.soap.service.transportationbookingsystem.exalt.com/personSoapClient/deleteUserByIdResponse", fault = {
        @FaultAction(className = personSoapClient.NotFoundException_Exception.class, value = "http://client.soap.service.transportationbookingsystem.exalt.com/personSoapClient/deleteUserById/Fault/NotFoundException")
    })
    public void deleteUserById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws personSoapClient.NotFoundException_Exception
    ;

}
