
package TripSoapClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TripSoapClientService", targetNamespace = "http://Client.SOAP_WebServices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TripSoapClientService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteBusTripById")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "DeleteBusTripById", targetNamespace = "http://Client.SOAP_WebServices/", className = "TripSoapClient.DeleteBusTripById")
    @ResponseWrapper(localName = "DeleteBusTripByIdResponse", targetNamespace = "http://Client.SOAP_WebServices/", className = "TripSoapClient.DeleteBusTripByIdResponse")
    @Action(input = "http://Client.SOAP_WebServices/TripSoapClientService/DeleteBusTripByIdRequest", output = "http://Client.SOAP_WebServices/TripSoapClientService/DeleteBusTripByIdResponse")
    public String deleteBusTripById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteTrainTripById")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "DeleteTrainTripById", targetNamespace = "http://Client.SOAP_WebServices/", className = "TripSoapClient.DeleteTrainTripById")
    @ResponseWrapper(localName = "DeleteTrainTripByIdResponse", targetNamespace = "http://Client.SOAP_WebServices/", className = "TripSoapClient.DeleteTrainTripByIdResponse")
    @Action(input = "http://Client.SOAP_WebServices/TripSoapClientService/DeleteTrainTripByIdRequest", output = "http://Client.SOAP_WebServices/TripSoapClientService/DeleteTrainTripByIdResponse")
    public String deleteTrainTripById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteFlightById")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "DeleteFlightById", targetNamespace = "http://Client.SOAP_WebServices/", className = "TripSoapClient.DeleteFlightById")
    @ResponseWrapper(localName = "DeleteFlightByIdResponse", targetNamespace = "http://Client.SOAP_WebServices/", className = "TripSoapClient.DeleteFlightByIdResponse")
    @Action(input = "http://Client.SOAP_WebServices/TripSoapClientService/DeleteFlightByIdRequest", output = "http://Client.SOAP_WebServices/TripSoapClientService/DeleteFlightByIdResponse")
    public String deleteFlightById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
