
package tripSoapClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "tripSoapClient", targetNamespace = "http://client.soap.service.transportationbookingsystem.exalt.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TripSoapClient {


    /**
     * 
     * @param arg0
     * @throws tripSoapClient.NotFoundException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteBusTripById", targetNamespace = "http://client.soap.service.transportationbookingsystem.exalt.com/", className = "tripSoapClient.DeleteBusTripById")
    @ResponseWrapper(localName = "deleteBusTripByIdResponse", targetNamespace = "http://client.soap.service.transportationbookingsystem.exalt.com/", className = "tripSoapClient.DeleteBusTripByIdResponse")
    @Action(input = "http://client.soap.service.transportationbookingsystem.exalt.com/tripSoapClient/deleteBusTripByIdRequest", output = "http://client.soap.service.transportationbookingsystem.exalt.com/tripSoapClient/deleteBusTripByIdResponse", fault = {
        @FaultAction(className = tripSoapClient.NotFoundException_Exception.class, value = "http://client.soap.service.transportationbookingsystem.exalt.com/tripSoapClient/deleteBusTripById/Fault/NotFoundException")
    })
    public void deleteBusTripById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws tripSoapClient.NotFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws tripSoapClient.NotFoundException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteTrainTripById", targetNamespace = "http://client.soap.service.transportationbookingsystem.exalt.com/", className = "tripSoapClient.DeleteTrainTripById")
    @ResponseWrapper(localName = "deleteTrainTripByIdResponse", targetNamespace = "http://client.soap.service.transportationbookingsystem.exalt.com/", className = "tripSoapClient.DeleteTrainTripByIdResponse")
    @Action(input = "http://client.soap.service.transportationbookingsystem.exalt.com/tripSoapClient/deleteTrainTripByIdRequest", output = "http://client.soap.service.transportationbookingsystem.exalt.com/tripSoapClient/deleteTrainTripByIdResponse", fault = {
        @FaultAction(className = tripSoapClient.NotFoundException_Exception.class, value = "http://client.soap.service.transportationbookingsystem.exalt.com/tripSoapClient/deleteTrainTripById/Fault/NotFoundException")
    })
    public void deleteTrainTripById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws tripSoapClient.NotFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws tripSoapClient.NotFoundException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteFlightById", targetNamespace = "http://client.soap.service.transportationbookingsystem.exalt.com/", className = "tripSoapClient.DeleteFlightById")
    @ResponseWrapper(localName = "deleteFlightByIdResponse", targetNamespace = "http://client.soap.service.transportationbookingsystem.exalt.com/", className = "tripSoapClient.DeleteFlightByIdResponse")
    @Action(input = "http://client.soap.service.transportationbookingsystem.exalt.com/tripSoapClient/deleteFlightByIdRequest", output = "http://client.soap.service.transportationbookingsystem.exalt.com/tripSoapClient/deleteFlightByIdResponse", fault = {
        @FaultAction(className = tripSoapClient.NotFoundException_Exception.class, value = "http://client.soap.service.transportationbookingsystem.exalt.com/tripSoapClient/deleteFlightById/Fault/NotFoundException")
    })
    public void deleteFlightById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws tripSoapClient.NotFoundException_Exception
    ;

}
