
package tripSoapClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "tripSoapClientService", targetNamespace = "http://client.soap.service.transportationbookingsystem.exalt.com/", wsdlLocation = "http://DESKTOP-VK3DF3H:8080/transportation-booking-system-1.0-SNAPSHOT/tripSoapClientService?wsdl")
public class TripSoapClientService
    extends Service
{

    private final static URL TRIPSOAPCLIENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRIPSOAPCLIENTSERVICE_EXCEPTION;
    private final static QName TRIPSOAPCLIENTSERVICE_QNAME = new QName("http://client.soap.service.transportationbookingsystem.exalt.com/", "tripSoapClientService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://DESKTOP-VK3DF3H:8080/transportation-booking-system-1.0-SNAPSHOT/tripSoapClientService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRIPSOAPCLIENTSERVICE_WSDL_LOCATION = url;
        TRIPSOAPCLIENTSERVICE_EXCEPTION = e;
    }

    public TripSoapClientService() {
        super(__getWsdlLocation(), TRIPSOAPCLIENTSERVICE_QNAME);
    }

    public TripSoapClientService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRIPSOAPCLIENTSERVICE_QNAME, features);
    }

    public TripSoapClientService(URL wsdlLocation) {
        super(wsdlLocation, TRIPSOAPCLIENTSERVICE_QNAME);
    }

    public TripSoapClientService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRIPSOAPCLIENTSERVICE_QNAME, features);
    }

    public TripSoapClientService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TripSoapClientService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns TripSoapClient
     */
    @WebEndpoint(name = "tripSoapClientPort")
    public tripSoapClient.TripSoapClient getTripSoapClientPort() {
        return super.getPort(new QName("http://client.soap.service.transportationbookingsystem.exalt.com/", "tripSoapClientPort"), TripSoapClient.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TripSoapClient
     */
    @WebEndpoint(name = "tripSoapClientPort")
    public TripSoapClient getTripSoapClientPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://client.soap.service.transportationbookingsystem.exalt.com/", "tripSoapClientPort"), TripSoapClient.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRIPSOAPCLIENTSERVICE_EXCEPTION!= null) {
            throw TRIPSOAPCLIENTSERVICE_EXCEPTION;
        }
        return TRIPSOAPCLIENTSERVICE_WSDL_LOCATION;
    }

}
