
package VehicleSoapClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VehicleSoapClientService", targetNamespace = "http://Client.SOAP_WebServices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VehicleSoapClientService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteTrainById")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "DeleteTrainById", targetNamespace = "http://Client.SOAP_WebServices/", className = "VehicleSoapClient.DeleteTrainById")
    @ResponseWrapper(localName = "DeleteTrainByIdResponse", targetNamespace = "http://Client.SOAP_WebServices/", className = "VehicleSoapClient.DeleteTrainByIdResponse")
    @Action(input = "http://Client.SOAP_WebServices/VehicleSoapClientService/DeleteTrainByIdRequest", output = "http://Client.SOAP_WebServices/VehicleSoapClientService/DeleteTrainByIdResponse")
    public String deleteTrainById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeletePlaneById")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "DeletePlaneById", targetNamespace = "http://Client.SOAP_WebServices/", className = "VehicleSoapClient.DeletePlaneById")
    @ResponseWrapper(localName = "DeletePlaneByIdResponse", targetNamespace = "http://Client.SOAP_WebServices/", className = "VehicleSoapClient.DeletePlaneByIdResponse")
    @Action(input = "http://Client.SOAP_WebServices/VehicleSoapClientService/DeletePlaneByIdRequest", output = "http://Client.SOAP_WebServices/VehicleSoapClientService/DeletePlaneByIdResponse")
    public String deletePlaneById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteBusById")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "DeleteBusById", targetNamespace = "http://Client.SOAP_WebServices/", className = "VehicleSoapClient.DeleteBusById")
    @ResponseWrapper(localName = "DeleteBusByIdResponse", targetNamespace = "http://Client.SOAP_WebServices/", className = "VehicleSoapClient.DeleteBusByIdResponse")
    @Action(input = "http://Client.SOAP_WebServices/VehicleSoapClientService/DeleteBusByIdRequest", output = "http://Client.SOAP_WebServices/VehicleSoapClientService/DeleteBusByIdResponse")
    public String deleteBusById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
