
package VehicleSoapClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VehicleSoapClientServiceService", targetNamespace = "http://Client.SOAP_WebServices/", wsdlLocation = "http://DESKTOP-VK3DF3H:8080/Sample_Project-1.0-SNAPSHOT/VehicleSoapClientServiceService?wsdl")
public class VehicleSoapClientServiceService
    extends Service
{

    private final static URL VEHICLESOAPCLIENTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException VEHICLESOAPCLIENTSERVICESERVICE_EXCEPTION;
    private final static QName VEHICLESOAPCLIENTSERVICESERVICE_QNAME = new QName("http://Client.SOAP_WebServices/", "VehicleSoapClientServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://DESKTOP-VK3DF3H:8080/Sample_Project-1.0-SNAPSHOT/VehicleSoapClientServiceService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VEHICLESOAPCLIENTSERVICESERVICE_WSDL_LOCATION = url;
        VEHICLESOAPCLIENTSERVICESERVICE_EXCEPTION = e;
    }

    public VehicleSoapClientServiceService() {
        super(__getWsdlLocation(), VEHICLESOAPCLIENTSERVICESERVICE_QNAME);
    }

    public VehicleSoapClientServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VEHICLESOAPCLIENTSERVICESERVICE_QNAME, features);
    }

    public VehicleSoapClientServiceService(URL wsdlLocation) {
        super(wsdlLocation, VEHICLESOAPCLIENTSERVICESERVICE_QNAME);
    }

    public VehicleSoapClientServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VEHICLESOAPCLIENTSERVICESERVICE_QNAME, features);
    }

    public VehicleSoapClientServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VehicleSoapClientServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns VehicleSoapClientService
     */
    @WebEndpoint(name = "VehicleSoapClientServicePort")
    public VehicleSoapClient.VehicleSoapClientService getVehicleSoapClientServicePort() {
        return super.getPort(new QName("http://Client.SOAP_WebServices/", "VehicleSoapClientServicePort"), VehicleSoapClientService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VehicleSoapClientService
     */
    @WebEndpoint(name = "VehicleSoapClientServicePort")
    public VehicleSoapClientService getVehicleSoapClientServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Client.SOAP_WebServices/", "VehicleSoapClientServicePort"), VehicleSoapClientService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VEHICLESOAPCLIENTSERVICESERVICE_EXCEPTION!= null) {
            throw VEHICLESOAPCLIENTSERVICESERVICE_EXCEPTION;
        }
        return VEHICLESOAPCLIENTSERVICESERVICE_WSDL_LOCATION;
    }

}
