
package vehicleSoapClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "vehicleSoapClient", targetNamespace = "http://client.soap.service.transportationbookingsystem.exalt.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VehicleSoapClient {


    /**
     * 
     * @param arg0
     * @throws NotFoundException_Exception
     * @throws RestrictDeleteException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteBusById", targetNamespace = "http://client.soap.service.transportationbookingsystem.exalt.com/", className = "vehicleSoapClient.DeleteBusById")
    @ResponseWrapper(localName = "deleteBusByIdResponse", targetNamespace = "http://client.soap.service.transportationbookingsystem.exalt.com/", className = "vehicleSoapClient.DeleteBusByIdResponse")
    @Action(input = "http://client.soap.service.transportationbookingsystem.exalt.com/vehicleSoapClient/deleteBusByIdRequest", output = "http://client.soap.service.transportationbookingsystem.exalt.com/vehicleSoapClient/deleteBusByIdResponse", fault = {
        @FaultAction(className = vehicleSoapClient.RestrictDeleteException_Exception.class, value = "http://client.soap.service.transportationbookingsystem.exalt.com/vehicleSoapClient/deleteBusById/Fault/RestrictDeleteException"),
        @FaultAction(className = vehicleSoapClient.NotFoundException_Exception.class, value = "http://client.soap.service.transportationbookingsystem.exalt.com/vehicleSoapClient/deleteBusById/Fault/NotFoundException")
    })
    public void deleteBusById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws vehicleSoapClient.NotFoundException_Exception, vehicleSoapClient.RestrictDeleteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws NotFoundException_Exception
     * @throws RestrictDeleteException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deletePlaneById", targetNamespace = "http://client.soap.service.transportationbookingsystem.exalt.com/", className = "vehicleSoapClient.DeletePlaneById")
    @ResponseWrapper(localName = "deletePlaneByIdResponse", targetNamespace = "http://client.soap.service.transportationbookingsystem.exalt.com/", className = "vehicleSoapClient.DeletePlaneByIdResponse")
    @Action(input = "http://client.soap.service.transportationbookingsystem.exalt.com/vehicleSoapClient/deletePlaneByIdRequest", output = "http://client.soap.service.transportationbookingsystem.exalt.com/vehicleSoapClient/deletePlaneByIdResponse", fault = {
        @FaultAction(className = vehicleSoapClient.NotFoundException_Exception.class, value = "http://client.soap.service.transportationbookingsystem.exalt.com/vehicleSoapClient/deletePlaneById/Fault/NotFoundException"),
        @FaultAction(className = vehicleSoapClient.RestrictDeleteException_Exception.class, value = "http://client.soap.service.transportationbookingsystem.exalt.com/vehicleSoapClient/deletePlaneById/Fault/RestrictDeleteException")
    })
    public void deletePlaneById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws vehicleSoapClient.NotFoundException_Exception, vehicleSoapClient.RestrictDeleteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws NotFoundException_Exception
     * @throws RestrictDeleteException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteTrainById", targetNamespace = "http://client.soap.service.transportationbookingsystem.exalt.com/", className = "vehicleSoapClient.DeleteTrainById")
    @ResponseWrapper(localName = "deleteTrainByIdResponse", targetNamespace = "http://client.soap.service.transportationbookingsystem.exalt.com/", className = "vehicleSoapClient.DeleteTrainByIdResponse")
    @Action(input = "http://client.soap.service.transportationbookingsystem.exalt.com/vehicleSoapClient/deleteTrainByIdRequest", output = "http://client.soap.service.transportationbookingsystem.exalt.com/vehicleSoapClient/deleteTrainByIdResponse", fault = {
        @FaultAction(className = vehicleSoapClient.NotFoundException_Exception.class, value = "http://client.soap.service.transportationbookingsystem.exalt.com/vehicleSoapClient/deleteTrainById/Fault/NotFoundException"),
        @FaultAction(className = vehicleSoapClient.RestrictDeleteException_Exception.class, value = "http://client.soap.service.transportationbookingsystem.exalt.com/vehicleSoapClient/deleteTrainById/Fault/RestrictDeleteException")
    })
    public void deleteTrainById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws vehicleSoapClient.NotFoundException_Exception, vehicleSoapClient.RestrictDeleteException_Exception
    ;

}
